- name: "Installing podman (dnf)" 
  when: ansible_facts['os_family'] == "RedHat"
  dnf:
    name: 
      - podman
    state: latest    
- name: "Installing Docker (apt Generic)" 
  when: ansible_facts['os_family']|lower == 'debian'
  apt:
    name: 
      - docker.io
      - docker-compose
    state: latest
- name: Python Docker module
  pip:
    name: docker
