---
- name: Bootstrap 
  hosts: GMod-TTT
  become: true
  tasks:
    - name: Prerequsits [apt]
      apt:
        name: "{{ packages }}"
        state: latest
        install_recommends: no
      vars:
        packages:
          - lib32gcc1
          - gcc-multilib
          - ca-certificates
    - name: Add Services
      group:
        name: Services 
        state: present
    - name: Add Ansible Local User
      user:
        name: ServerOP 
        comment: 
        password_lock: yes
        groups: Services 
        append: yes
        create_home: false
    - name: "Make Server Directory"   
      file:
        path: "/opt/Gmod-TTT/"
        state: directory
        owner: ServerOP 
        group: Services
        mode: "0770"
    - name: Get SteamCMD
      get_url:
        url: http://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        dest: /tmp/steamcmd_linux.tar.gz
        mode: "0660"
        owner: ServerOP
        group: Services
    - name: De-Tar
      unarchive:
        remote_src: yes
        src: /tmp/steamcmd_linux.tar.gz
        dest: /opt/Gmod-TTT/
    - name: Test SteamCMD
      cmd: "/opt/Gmod-TTT/steamcmd.sh +quit"
    - name: Download GMod Server Files
      cmd: "/opt/Gmod-TTT/steamcmd.sh +login anonymous +force_install_dir Server1 +app_update 4020 validate +quit"
