---
  - name: BootStrap
    hosts: all
    become: true
    vars:
      packages:
        - vim
        - python3-pip
        - tuned
        - htop
        - puppet
    roles:
      - Service-Account
    tasks:
      - name: SeLinuxPython [dnf]
        when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] >= "8"
        dnf:
          name: python3-libselinux
          state: latest
      - name: Update Packages
        when: ansible_facts['os_family'] == "RedHat" 
        dnf:
          name: "*"
          state: latest
      - name: packages to install
        when: ansible_facts['os_family'] == "RedHat" 
        dnf:
          name: "{{ packages }}"
          state: latest
      - name: Systemctl tuned service
        shell: "systemctl start tuned.service"
      - name: tuned-adm activated
        shell: "tuned-adm profile latency-performance virtual-host"
      - name: enable powertools
        ini_file:
          path: /etc/yum.repos.d/CentOS-PowerTools.repo
          section: PowerTools
          option: enabled
          value: "1"
