- name: "Add Local User {{ username }} "
  user:
    name: "{{ username }}"
    comment: Command and Control Account
    password_lock: " {{ lock }} "
    groups: "{{ groups }}"   
    append: yes
    create_home: true
- name: "Make .ssh Key"   
  file:
    path: "/home/{{ username }}/.ssh/"
    state: directory
    owner: "{{ username }}" 
    group: "{{ username }}" 
    mode: "0700"
- name: Make Authorised Key      
  file:
    path: "/home/{{ username }}/.ssh/authorized_keys"
    state: touch
    owner: GlitchWraith
    group: GlitchWraith
    mode: "0600"
- name: Add Publickey 
  lineinfile:
    path: "/home/{{ username }}/.ssh/authorized_keys"
    line: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQCa6LFwhsOz7tykqncVgxZtw4kca4YixdY9gQT5qsFONo6DMxMUMp6FoDrJWMRNh62b17jIYSeXj7w/jyZGfsF0Ze478gPc7Kt/dlU20/4cs3pjwhJ2CAiSjm/EXCyRUiGUcvJnK3d77ox++jMIxuIe4BjErKC1fzxePFqefUQ4a9Q+SslbUvlUIXtr+xDpT0IMAX341L0GlUyNfj8mZJGOHGUgUsKLWrToHUMd1S6vayyhV/Ao0hLjEPBxZc7Xxrhm/XmKNl/GAGBZO2woc3+4tsnUfphW9cfJOTFpaHzKHCYAM4ycwHQF4LuwUdgNx6sNpF0SAbEwml+otvu4643fdtntas2kPcDqbBYUoA+vNQhuBo0x8n5uAZqk8Q8TUY8rv8JlgD2JulHaEy3lHnlGwNE4IqUSbeGwH1dcCMMxBZzyYqosOqFMk5l6qY/B5bFxCWL4KF69UzUy0tFzs3pWbXvca+/rNF8FeQxzhCv2y0ft0BS9pYvQPHkOc9rQUo/Ve5JCpIZkZYIa9ZyQBN4pw8pwDkvA0kIWcwsE4JHoQ4hzk1NHFXehs3vnULVd0CCaC5plhbt3yMzLQfWyUBQbnUOiadWDIHsLGacPyMQIV0SyWefZeJnd2aUrqn6sQi+qXbvHbQYJGaIfYb6/g1pfI4u705fikJOekCyvewWXByTO5T5T5GW4PDGXe1jKYI9WUzb7M36MZqMGY4Ij2epalIXLSb6sOhNa9qwvggwkL/eefKwk/g6VEYP/lZxUmO0f5LeiU/5GnE71geua51bcreJd+O45gRmexDKmoLH1Zs7hBYFbddp8aTP0pFNyKITmmzXNpazLeaJ1jZFpc0C2TOcIJpLXs33wldbw5XcvXFfX+gRkM2ID9XVFvkakvK8HwUlCC5KQbgSAypAokY1A6mUO69xeLR8BUzLCtmzujLFbaSg4ayWT7lsWlPAk9o7DI71DOEVTxs4Xazr7R6Un8uZFQO4EKLGefuTAfv4NI25g2UjV86TTEW60M5sHhc4eUJ1NS8HJFLTLh86fwpquQLMdo12YxQn5RVtU9FRKpnXutIZU6puNqMgXoG160PJvezG0sBhuHnAW+eXc+EnHbD31mAbfqTUyMf5GFErk5Yd76c3oMj5vChGN0gXZ1LxQn1gUwW8k+CF+0EBGReNjqyXfRpzu+YHFfZgN3gjKaFoMbOJJacgnSqtVIRLgDSvm8YVGk876p6ShtwcCg0TkHOPHPWGpQc+bXYzS72NBDVjSjR3+Y+UWsYZV1vdps6gQiFlTfzFEGudvSVl1vQTVcMcy9t7eMZKyuh3eQGrpsGgHt3lQQ2usQsVi2TPtGPfWFNtG00kaZEewjp6Eh/PJ _Tibbles__@Valkyrie.Core.RealmOfTibbles.XYZ"

- name: Add Publickey 
  lineinfile:
    path: "/home/{{ username }}/.ssh/authorized_keys"
    line: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDbe1nZluN+ZpnX/Rk6vMl8uLBYXmE2EmRmAWFKdihJz6qbQJOupDidQ6GjjsQ8FrFV1bQ3Dj24v4zutOV8j16VQYvPC9jswz7rgNu2s1x9AHboDsJziWQb8nMZKuUV6IcJOOuDh0H0SCkApUulyXz0diYn5FCzwfMjg0AtqDUbFMJ3LXVHXOad+g9cV3pNr33qc8vdoH5RwNX4yb/dH8ZxMHTRjYIMxSe2fXMe/az85JQGyepzgD9YUtoxvtShHTbChTGI6hPCzpJf6hqfqKq849yzoblaxefIH8XSpfG1I5Y0GhNb34vvXS7LXe53bWkXvVKmmu2MqUoeBK9+H9hK2Idz/0Ut5TaB7hST4LLtU0bBm0ILWbpvolXZuShn834jV5oEHMzz93x+W2XsRrzMEmAKpt6Xws1SpvFwG8ywVfRcWRrs1X7ibyTfMBHmrpwcoMamlDyujo2j09QSY3yuf4Wyp6BmUvLb7+TFkkBhKqEv0soKHumUlI3gdYfImCrBK0CPSl0icCrvVjwvUg422Lq3a4ReXh9ySve1zJpLgYMbBog9FdsULkP7Pjj+sD30tcTzJluh37dV/BFVUTG2Si5p0pSiUUVLyIeEvpcaYQn/PeMj6ZxG5alHAU1w0aXNbEHYeRWzzSWts4lub/bzsT4gBqo/g1RLy3mQtavUXQ=="
- name: Add Publickey 
  lineinfile:
    path: "/home/{{ username }}/.ssh/authorized_keys"
    line: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxGkUItxk9179CE99yW5MJk55a29fQKfjnIZa4pcwv4ZVDOdctmjjGYURlW1FTK02W+Zi0ANDI1L3XEt1UFFsyU1PtcgmiELHkALELYwT0DIXt8eDMrf703gr7rQKiKjV5FcrPW1d5poPmh/33/QvRzfyZDY+gkIRVJavsamCR63Qk/GWMEPqi6CF/hhqlczUBcayUPJgUH9brQRtDa92l7nTNnQGNkRcnw/Q692OiU0Vd5BiEBqU97uftPeUZdNdJ2K198P6wVMb7pJNeRTBHo+Z9A/kHNUZSFXLJ7VCP/+nJBsGjiS4IEfj5oGPGeUJWYBR8gvOPf+JHrHuq28TPsPAzTw94Gqh1Q0C0sGwxO3iL783GW10XGNI2wbVeQ7w7bRPgqZXVD1ixV5g0bDcqGdiHKA/SQOWOiryYke1Ji04UIaJIGEt7Uqo99pfle527cT7XLLF6Fx7yD80Ckh8VyS8mZfnivhVOnhBby1yho7XW/Qe6oG8OfBHUfbU27q45MCYxKmrxbaZykvEJ90nLqjEf2mP36RhwAxqO1GZinRmmYpnR9zko8qygaNzPGkJFUVv73T0ZZPNmG/rXT4HlyVkz/wbFonf6nciTSTW6W7tbre8SLuMqrDomv7Kx8IE2G3hFVkW+Bl8f8tYPuk5VGKlFvpMETQ5WKmR2m8fy4Q=="
