- name: Docker Group
  group:
    name: docker
    state: present
- name: Libvirt Group
  group:
    name: libvirt
    state: present
- name: Add ShellLink Local User ServiceLink
  user:
    name: ServiceLink
    comment: Command and Control Account
    password_lock: yes
    groups: docker,libvirt
    append: yes
    create_home: true
- name: Wheel Group
  when: ansible_facts['os_family'] == "RedHat"
  user:
    name: ServiceLink
    groups: wheel
    append: yes
- name: sudo Group
  when: ansible_facts['distribution'] == "Ubuntu"
  user:
    name: ServiceLink
    groups: sudo
    append: yes
- name: Make ServiceLink sudo Passwordless
  lineinfile:
    path: /etc/sudoers
    state: present
    line: "ServiceLink  ALL=(ALL)       NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s
- name: "Make .ssh Key"   
  file:
    path: "/home/ServiceLink/.ssh/"
    state: directory
    owner: ServiceLink 
    group: ServiceLink 
    mode: "0700"
- name: Make Authorised Key      
  file:
    path: "/home/ServiceLink/.ssh/authorized_keys"
    state: touch
    owner: ServiceLink
    group: ServiceLink
    mode: "0600"
- name: Add Publickey 
  lineinfile:
    path: "/home/ServiceLink/.ssh/authorized_keys"
    line: "{{ item }}"
  loop: "{{ SSH_SERVICELINK_SSH }}"
